"""Tests for Salus OneTouch rule buttons."""

from unittest.mock import MagicMock

from custom_components.salus_it600_cloud import button

from . import fixtures
from .helpers import create_coordinator


async def _buttons() -> tuple[list, object]:
    coordinator, connection, _ = await create_coordinator()
    entry = MagicMock()
    entry.runtime_data = coordinator
    add_entities = MagicMock()
    await button.async_setup_entry(MagicMock(), entry, add_entities)
    return add_entities.call_args.args[0], connection


async def test_buttons_only_for_user_created_rules() -> None:
    """Rules generated by the Salus app (names starting with underscore) get no button; ids stay unchanged."""

    entities, _ = await _buttons()

    assert [entity.name for entity in entities] == ["Apartmán A Vypnout topení (Stand-by)"]
    assert entities[0].unique_id == f"salus_it600_cloud_{fixtures.GATEWAY_ID}_onetouch_{fixtures.RULE_ID}"


async def test_press_triggers_rule_through_gateway_shadow() -> None:
    """Pressing the button triggers the rule on the gateway without extra API calls."""

    entities, connection = await _buttons()

    await entities[0].async_press()

    assert connection.published == [
        (fixtures.GATEWAY_CODE, "000000000001", {"ep0:sRule:SetTriggerRule": fixtures.RULE_TRIGGER_KEY})
    ]
